^shot$: user.screenshot()
^shot clip$: user.screenshot_clipboard()
^shot <number_small>$: user.screenshot(number_small)
^shot <number_small> clip$: user.screenshot_clipboard(number_small)
^shot window$: user.screenshot_window()
^shot window clip$: user.screenshot_window_clipboard()
^shot select$: user.screenshot_selection()
^shot select clip$: user.screenshot_selection_clip()
^shot settings$: user.screenshot_settings()
