^screenshot file$: user.screenshot()
^screenshot clip$: user.screenshot_clipboard()
^screenshot <number_small>$: user.screenshot(number_small)
^screenshot <number_small> clip$: user.screenshot_clipboard(number_small)
^screenshot window$: user.screenshot_window()
^screenshot window clip$: user.screenshot_window_clipboard()
^screenshot select$: user.screenshot_selection()
(^screenshot select clip$ | ^screenshot$): user.screenshot_selection_clip()
^screenshot settings$: user.screenshot_settings()
