# This file is autogenerated by sounds_test_generate_active_talon.py
# Sound test - logs parrot sounds with timestamps when sound test mode is active
# Log output: sounds_test.log (see sounds_test.py in this folder)

mode: user.sound_test
-
sounds test off:
    mode.disable("user.sound_test")
    mode.enable("command")
    app.notify("Sound test mode OFF")

parrot(cha): user.sound_test_log('cha')
parrot(cha:repeat): user.sound_test_log('cha:repeat')
parrot(cha:stop): user.sound_test_log('cha:stop')
parrot(clop): user.sound_test_log('clop')
parrot(kuh): user.sound_test_log('kuh')
parrot(motor): user.sound_test_log('motor')
parrot(motor:repeat): user.sound_test_log('motor:repeat')
parrot(motor:stop): user.sound_test_log('motor:stop')
parrot(puh): user.sound_test_log('puh')
parrot(shh): user.sound_test_log('shh')
parrot(shh:repeat): user.sound_test_log('shh:repeat')
parrot(shh:stop): user.sound_test_log('shh:stop')
parrot(snore): user.sound_test_log('snore')
parrot(snore:repeat): user.sound_test_log('snore:repeat')
parrot(snore:stop): user.sound_test_log('snore:stop')
parrot(spit): user.sound_test_log('spit')
parrot(sss): user.sound_test_log('sss')
parrot(sss:repeat): user.sound_test_log('sss:repeat')
parrot(sss:stop): user.sound_test_log('sss:stop')
parrot(tih): user.sound_test_log('tih')
parrot(whistle): user.sound_test_log('whistle')
parrot(whistle:repeat): user.sound_test_log('whistle:repeat')
parrot(whistle:stop): user.sound_test_log('whistle:stop')
parrot(wince): user.sound_test_log('wince')
parrot(wince:repeat): user.sound_test_log('wince:repeat')
parrot(wince:stop): user.sound_test_log('wince:stop')
