"""
Generate sounds_test_active.talon from ~/.talon/parrot/model.json.

Reads the parrot model definition and produces a .talon file that logs
every detected sound during sound test mode.

Usage: python sounds_test_generate_active_talon.py
"""

import json
import os

SCRIPT_DIR = os.path.realpath(os.path.dirname(__file__))
MODEL_PATH = os.path.expanduser("~/.talon/parrot/model.json")
OUTPUT_PATH = os.path.join(SCRIPT_DIR, "sounds_test_active.talon")

EXCLUDED_SOUNDS = {"silence", "speech", "noise"}

HEADER = """\
# This file is autogenerated by sounds_test_generate_active_talon.py
# Sound test - logs parrot sounds with timestamps when sound test mode is active
# Log output: sounds_test.log (see sounds_test.py in this folder)

mode: user.sound_test
-
sounds test off:
    mode.disable("user.sound_test")
    mode.enable("command")
    app.notify("Sound test mode OFF")
"""


def load_model(path):
    """Load and return the model JSON."""
    with open(path) as f:
        return json.load(f)


def generate_parrot_lines(sounds):
    """Generate parrot rule lines from the sounds dict."""
    lines = []

    for name in sorted(sounds):
        if name in EXCLUDED_SOUNDS:
            continue

        duration_type = sounds[name]["duration_type"]

        lines.append(f"parrot({name}): user.sound_test_log('{name}')")

        if duration_type == "continuous":
            lines.append(f"parrot({name}:repeat): user.sound_test_log('{name}:repeat')")
            lines.append(f"parrot({name}:stop): user.sound_test_log('{name}:stop')")

    return lines


def write_talon_file(path, parrot_lines):
    """Write the complete .talon file."""
    with open(path, "w") as f:
        f.write(HEADER)
        f.write("\n")
        f.write("\n".join(parrot_lines))
        f.write("\n")


def main():
    model = load_model(MODEL_PATH)
    parrot_lines = generate_parrot_lines(model["sounds"])
    write_talon_file(OUTPUT_PATH, parrot_lines)

    print(f"Generated {OUTPUT_PATH}")
    print(f"  {len(parrot_lines)} parrot rules from {len(model['sounds'])} model sounds")


if __name__ == "__main__":
    main()
