tag: terminal
-
# Claude chat skills:
# - list-based commands from ~/.claude/commands/*.md (generated by python)
# - freeform fallback when needed

# List-based command takes priority.
chat {user.claude_skills}:
    insert("/{claude_skills}")
    key(tab)

# Freeform fallback for non-listed skills.
chat free <user.text>:
    user.claude_skill_insert(text)

# Regenerate list manually.
chat refresh skills:
    user.claude_skills_generate()

chat clear <user.text>:
    insert("/clear\n")
    sleep(100ms)
    user.claude_skill_insert(text)

option <number_small>:
    insert("{number_small}\n")

option no:
    insert("no\n")

option yes:
    insert("yes\n")

option proceed:
    insert("proceed\n")

option approve:
    insert("approve\n")

show pull request:
    insert("can you open the pull request in brave for me?\n")

show ticket:
    insert("can you open the ticket in brave for me?\n")

show project:
    insert("can you open the project in brave for me?\n")